using BOTB64.Engine;
using BOTB64.Engine.Net;
using BOTB64.Graphics.Vfx;
using BOTB64.Runtime;

namespace BOTB64.Entities
{
    /* Contains the internals for all effects in the game */
    public static class EffectProcessor
    {
        public static float Random(Game game, float min, float max)
        {
            double rng = game.Random();
            return (float)rng * max + (1 - (float)rng) * min;
        }

        public static bool Roll(Game game, float thresh)
        {
            return game.Random() < thresh;
        }

        public static void Heal(Game game, int charId, int amount)
        {
            game.RecordAndApply(new HealEvent { TargetID = charId, Amount = amount, Crit = false });
        }

        public static bool CheckLOS(Game game, int from, int to)
        {
            Character? fromChar = game.FindCharacter(from);
            Character? toChar = game.FindCharacter(to);

            if (fromChar == null || toChar == null)
                return false;

            var beam = HexAlgo.Beam(fromChar.Position, toChar.Position);
            foreach (Hex h in beam)
            {
                Tile? t = game.GetBoard().GetTile(h);
                if (t == null)
                    return false;
                if (!t.AllowsLos())
                    return false;
            }

            return true;
        }

        public static bool Damage(Game game, EffectContext ctx, Effect eff, int targetID, int baseDamage)
        {
            var target = game.FindCharacter(targetID);
            return Damage(game, ctx, eff, target, baseDamage);
        }

        public static bool Damage(Game game, EffectContext ctx, Effect eff, Character target, int baseDamage)
        {
            if (target == null)
                return false;
            var dmgCtx = new DamageContext(ctx.Invoker, ctx.Invoker, target);
            dmgCtx.DamageDone = baseDamage;
            dmgCtx.DamageType = eff.Type;
            dmgCtx.SourceType = eff.Source;
            AuraTriggerManager.Execute(dmgCtx, EffectTrigger.OnPreDamageDealt, AuraType.Character | AuraType.Tile);
            var preDamageDoer = dmgCtx.Invoker;
            dmgCtx.Invoker = dmgCtx.DamageTaker;
            AuraTriggerManager.Execute(dmgCtx, EffectTrigger.OnPreDamageTaken, AuraType.Character | AuraType.Tile);
            dmgCtx.Invoker = preDamageDoer;
            dmgCtx.DamageDone = CalcDamage(dmgCtx.DamageDoer, dmgCtx.DamageTaker, dmgCtx.DamageDone, eff.Scaling);
            dmgCtx.Crit = Roll(game, dmgCtx.DamageDoer.Crit.GetF());
            if (dmgCtx.Crit)
                dmgCtx.DamageDone = (int)(1.5 * dmgCtx.DamageDone);
            game.RecordAndApply(new DamageEvent { TargetID = dmgCtx.DamageTaker.GameID, Amount = dmgCtx.DamageDone, Crit = dmgCtx.Crit });
            game.RecordAndApply(new HealEvent { TargetID = dmgCtx.DamageDoer.GameID, Amount = CalcLifeSteal(dmgCtx.DamageDoer, dmgCtx.DamageDone, eff.Scaling) });
            if (dmgCtx.DamageDone > 0)
            {
                // dmgCtx (not ctx) so DamageAmount/Attacker/DamageTarget are available -
                // Invoker is still the attacker here (unchanged from dmgCtx's construction).
                AuraTriggerManager.Execute(dmgCtx, EffectTrigger.OnDamageDone, AuraType.Character | AuraType.Tile);
                if (dmgCtx.DamageTaker.Alive)
                {
                    // Invoker must be the defender here so aura iteration/scripts see
                    // things from their perspective; DamageDoer/DamageTaker still expose
                    // who actually attacked via the Attacker/DamageTarget Lua globals.
                    dmgCtx.Invoker = dmgCtx.DamageTaker;
                    AuraTriggerManager.Execute(dmgCtx, EffectTrigger.OnDamageTaken, AuraType.Character | AuraType.Tile);
                }
            }
            if (dmgCtx.DamageTaker.CurrentHP <= 0)
                Die(game, dmgCtx.DamageTaker.GameID);
            return true;
        }

        // Like Damage(targetID, amount), but lets the caller name the attacker explicitly
        // instead of assuming CurrentContext.Invoker - needed when a tile effect (owned by
        // whoever placed it) damages whoever triggers it (e.g. Storm terrain damaging
        // someone standing on it should be attributed to its caster, not the victim).
        public static bool DamageAs(Game game, Effect eff, int doerID, int targetID, int baseDamage)
        {
            Character? doer = game.FindCharacter(doerID);
            if (doer == null)
                return false;
            return Damage(game, new EffectContext(doer), eff, targetID, baseDamage);
        }

        // Direct resource gain/spend outside the normal spell-cost path - e.g. combo
        // points/bloodwell generated by combat events rather than by casting a spell.
        public static void ModifyResource(Game game, int charId, int delta)
        {
            game.RecordAndApply(new ResourceModifiedEvent { CharacterID = charId, Delta = delta });
        }

        public static int GetAuraStacks(Game game, int charId, int auraId)
        {
            var aura = game.FindCharacter(charId)?.CurrentAuras.FirstOrDefault(a => a.ID == auraId);
            return aura?.CurrentStacks ?? 0;
        }

        public static bool HasTileEffect(Game game, int q, int r, int tileEffectId)
        {
            var tile = game.GetBoard().GetTile(new Hex(q, r));
            return tile != null && tile.Effects.Any(e => e.ID == tileEffectId);
        }

        public static List<Hex> FindTileEffectPositions(Game game, int tileEffectId)
        {
            var result = new List<Hex>();
            foreach (var row in game.GetBoard().Tiles)
                foreach (var tile in row)
                    if (tile.Effects.Any(e => e.ID == tileEffectId))
                        result.Add(tile.AxialPosition);
            return result;
        }

        public static void RemoveTileEffect(Game game, int q, int r, int tileEffectId)
        {
            var hex = new Hex(q, r);
            var tile = game.GetBoard().GetTile(hex);
            if (tile != null && tile.Effects.Any(e => e.ID == tileEffectId))
                game.RecordAndApply(new TileEffectExpiredEvent { Position = hex, TileEffectID = tileEffectId });
        }

        public static void SetTileEffectParam(Game game, int q, int r, int tileEffectId, string key, float value)
        {
            var tile = game.GetBoard().GetTile(new Hex(q, r));
            if (tile == null || !tile.Effects.Any(e => e.ID == tileEffectId))
                return;
            game.RecordAndApply(new TileEffectParamSetEvent { Position = new Hex(q, r), TileEffectID = tileEffectId, Key = key, Value = value });
        }

        public static float GetTileEffectParam(Game game, int q, int r, int tileEffectId, string key)
        {
            var tile = game.GetBoard().GetTile(new Hex(q, r));
            var effect = tile?.Effects.FirstOrDefault(e => e.ID == tileEffectId);
            var param = effect?.Parameters.FirstOrDefault(p => p.Name == key);
            return param?.GetFloat(0f) ?? 0f;
        }

        public static bool ForceMove(Game game, int charID, Hex destination)
        {
            Character? character = game.FindCharacter(charID);
            if (character == null)
                return false;
            if (character.HasSpecialEffect(AuraSpecialEffect.KnockbackImmune))
                return false;

            Tile? tile = game.GetBoard().GetTile(destination);
            if (tile == null || !tile.IsPassable())
                return false;

            game.RecordAndApply(new ForcedMoveEvent { CharacterID = charID, Step = destination });

            var ctx = new EffectContext(character);
            AuraTriggerManager.Execute(ctx, EffectTrigger.OnMove, AuraType.Character | AuraType.Tile);

            return true;
        }

        public static bool ApplyAura(Game game, int ownerID, int targetID, int auraID, int stacksToAdd)
        {
            Character? owner = game.FindCharacter(ownerID);
            Character? target = game.FindCharacter(targetID);
            if (owner == null || target == null)
                return false;

            Aura? template = AuraTriggerManager.GetAura(auraID);
            if (template == null)
                return false;

            var existing = target.CurrentAuras.FirstOrDefault(a => a.ID == auraID);
            int currentStacks = existing?.CurrentStacks ?? 0;
            int finalStacks = Math.Min(currentStacks + stacksToAdd, template.MaxStacks);

            // Invoker must be the target/wearer (mirrors DropAura) so aura iteration sees
            // the aura on the correct character's list - every existing caller happens to
            // self-apply (owner == target), which is why this was never visibly wrong before.
            var auraCtx = new ApplyAuraContext(target, owner, target, template);
            game.RecordAndApply(new ApplyAuraEvent { OwnerID = ownerID, TargetID = targetID, AuraID = auraID, FinalStacks = finalStacks });
            AuraTriggerManager.Execute(auraCtx, EffectTrigger.OnApply, AuraType.Character);
            AuraTriggerManager.Execute(auraCtx, EffectTrigger.OnOtherAuraApplied, AuraType.Character);
            return true;
        }

        // EffectProcessor.cs — new method, alongside ApplyAura
        public static bool ApplyTileEffect(Game game, int ownerID, Hex position, int tileEffectID, int duration)
        {
            Character? owner = game.FindCharacter(ownerID);
            var tile = game.GetBoard().GetTile(position);
            if (owner == null || tile == null)
                return false;
            TileEffect? template = AuraTriggerManager.GetTileEffect(tileEffectID); // mirrors GetAura
            if (template == null)
                return false;
            game.RecordAndApply(new ApplyTileEffectEvent { OwnerID = ownerID, Position = position, TileEffectID = tileEffectID, Duration = duration });
            var tileCtx = new EffectContext(owner);
            AuraTriggerManager.Execute(tileCtx, EffectTrigger.OnApply, AuraType.Tile);
            AuraTriggerManager.Execute(tileCtx, EffectTrigger.OnApplyTileEffect, AuraType.Character);
            return true;
        }

        public static void Die(Game game, int charID)
        {
            game.RecordAndApply(new DeathEvent { CharacterID = charID }); 
            var character = game.FindCharacter(charID); 
            if (character != null) 
                AuraTriggerManager.Execute(new EffectContext(character), EffectTrigger.OnDeath, AuraType.Character | AuraType.Tile);
        }

        public static void SetAuraParam(Game game, int wearerId, int auraId, string key, float value)
        {
            var wearer = game.FindCharacter(wearerId);
            var aura = wearer?.CurrentAuras.FirstOrDefault(a => a.ID == auraId);
            if (aura == null) return;
            game.RecordAndApply(new AuraParamSetEvent { CharacterID = wearerId, AuraID = auraId, Key = key, Value = value });
        }

        public static float GetAuraParam(Game game, int wearerId, int auraId, string key)
        {
            var wearer = game.FindCharacter(wearerId);
            var aura = wearer?.CurrentAuras.FirstOrDefault(a => a.ID == auraId);
            var param = aura?.Parameters.FirstOrDefault(p => p.Name == key);
            return param?.GetFloat(0f) ?? 0f; // read-only — no event needed, same tier as GetHP
        }

        public static bool ModifyStat(Game game, int characterId, string statName, float addDelta, float mulDelta)
        {
            var character = game.FindCharacter(characterId);
            if (character == null) return false;

            if (!Enum.TryParse<StatType>(statName, ignoreCase: true, out var stat))
            {
                Logger.Log($"ModifyStat: unknown stat '{statName}'");
                return false;
            }

            game.RecordAndApply(new StatModifiedEvent
            {
                CharacterID = characterId,
                Stat = stat,
                AddDelta = addDelta,
                MulDelta = mulDelta
            });
            return true;
        }

        public static void DropAura(Game game, int charId, int auraId, int stacks)
        {
            Character? character = game.FindCharacter(charId);
            if(character == null) return;

            var existing = character.CurrentAuras.FirstOrDefault(a => a.ID == auraId);

            if(existing == null) 
                return;

            int currentStacks = existing?.CurrentStacks ?? 0;
            int finalStacks = Math.Min(currentStacks - stacks, existing.MaxStacks);

            // Triggers fire before the event is applied (unlike ApplyAura) so OnDropStack/
            // OnDrop scripts can still read the aura's own Parameters via GetAuraParam -
            // once FinalStacks <= 0, ApplyAuraEvent.Apply removes the aura from
            // CurrentAuras, and GetAuraParam looks it up fresh by ID each call, so it
            // would find nothing if the event ran first.
            var auraCtx = new ApplyAuraContext(existing.Wearer, existing.Owner, existing.Wearer, existing);
            AuraTriggerManager.Execute(auraCtx, EffectTrigger.OnDropStack, AuraType.Character);
            if(finalStacks <= 0)
                AuraTriggerManager.Execute(auraCtx, EffectTrigger.OnDrop, AuraType.Character);
            game.RecordAndApply(new ApplyAuraEvent { OwnerID = existing.Owner.GameID, TargetID = existing.Wearer.GameID, AuraID = existing.ID, FinalStacks = finalStacks });
        }

        // Drops every currently-worn aura tagged with the given special effect (e.g. all
        // Root or Slow debuffs) - used by cleanse effects like Pilaf's Unstoppable Force.
        public static void RemoveAurasWithSpecialEffect(Game game, int charId, AuraSpecialEffect effect)
        {
            Character? character = game.FindCharacter(charId);
            if (character == null)
                return;
            foreach (var aura in character.CurrentAuras.ToList())
                if (aura.SpecialEffect.HasFlag(effect))
                    DropAura(game, charId, aura.ID, aura.CurrentStacks);
        }

        public static void SpendAction(Game game, int characterID, bool fast)
        {
            game.RecordAndApply(new ActionSpentEvent { CharacterID = characterID, FastAction = fast });
        }

        // Moves a character step-by-step toward (towardQ,towardR), up to `steps` hexes,
        // reusing ForceMove per step (so KnockbackImmune/animation/OnMove all apply
        // normally). Stops before entering a wall tile and returns true in that case;
        // stops silently (returns false) if blocked by anything else (an occupant, an
        // impassable tile effect, or running out of steps) - "hit a wall" is meant
        // literally, not "got blocked for any reason".
        public static bool PullToward(Game game, int charId, int towardQ, int towardR, int steps)
        {
            Character? character = game.FindCharacter(charId);
            if (character == null)
                return false;

            var line = HexAlgo.Beam(character.Position, new Hex(towardQ, towardR));
            for (int i = 1; i <= steps && i < line.Count; i++)
            {
                Hex dest = line[i];
                Tile? tile = game.GetBoard().GetTile(dest);
                if (tile == null)
                    break;
                if (tile.Type == TileType.Wall)
                    return true;
                if (!tile.IsPassable())
                    break;
                ForceMove(game, charId, dest);
            }
            return false;
        }

        public static bool IsEnemy(Game game, int charID1, int charID2)
        {
            Character? a = game.FindCharacter(charID1);
            Character? b = game.FindCharacter(charID2);
            if (a == null || b == null)
                return false;
            return a.Faction != b.Faction;
        }

        public static int HexDistance(int q1, int r1, int q2, int r2)
        {
            return HexAlgo.HexDistance(new Hex(q1, r1), new Hex(q2, r2));
        }

        public static List<Hex> GetHexesInRadius(int q, int r, int radius)
        {
            var center = new Hex(q, r);
            var result = new List<Hex>();
            for (int dq = -radius; dq <= radius; dq++)
                for (int dr = -radius; dr <= radius; dr++)
                {
                    var h = new Hex(q + dq, r + dr);
                    if (HexAlgo.HexDistance(center, h) <= radius)
                        result.Add(h);
                }
            return result;
        }

        public static List<Hex> GetLine(int fromQ, int fromR, int toQ, int toR)
        {
            return HexAlgo.Beam(new Hex(fromQ, fromR), new Hex(toQ, toR));
        }

        public static bool TileBlocksLos(Game game, int q, int r)
        {
            Tile? tile = game.GetBoard().GetTile(new Hex(q, r));
            return tile == null || !tile.AllowsLos();
        }

        public static bool IsWall(Game game, int q, int r)
        {
            Tile? tile = game.GetBoard().GetTile(new Hex(q, r));
            return tile != null && tile.Type == TileType.Wall;
        }

        // Reduces HP as a spell cost rather than as damage - no mitigation, no on-damage
        // triggers, and it can never kill the payer (floors at 1 HP remaining).
        public static void PayHealthCost(Game game, int charId, int amount)
        {
            Character? character = game.FindCharacter(charId);
            if (character == null)
                return;
            int actual = Math.Min(amount, character.CurrentHP - 1);
            if (actual <= 0)
                return;
            game.RecordAndApply(new HealthCostEvent { CharacterID = charId, Amount = actual });
        }

        // Lua-facing VFX triggers. These must go through an IGameEvent (like every other
        // action here) rather than calling VfxManager directly - Lua effect scripts only
        // execute on the host, so the actual playback has to happen in Apply(), which every
        // client (including the host) replays from the broadcast event log.
        public static void PlayVfxInstant(Game game, string vfxId, int q, int r)
        {
            game.RecordAndApply(new PlayVfxEvent { VfxID = vfxId, Mode = VfxType.Instant, From = new Hex(q, r) });
        }

        public static void PlayVfxProjectile(Game game, string vfxId, int fromQ, int fromR, int toQ, int toR)
        {
            game.RecordAndApply(new PlayVfxEvent { VfxID = vfxId, Mode = VfxType.Projectile, From = new Hex(fromQ, fromR), To = new Hex(toQ, toR) });
        }

        public static void PlayVfxBeam(Game game, string vfxId, int fromQ, int fromR, int toQ, int toR)
        {
            game.RecordAndApply(new PlayVfxEvent { VfxID = vfxId, Mode = VfxType.Beam, From = new Hex(fromQ, fromR), To = new Hex(toQ, toR) });
        }

        public static bool MoveTileEffect(Game game, int ownerID, int fromQ, int fromR, int toQ, int toR, int tileEffectID, int duration)
        {
            var fromHex = new Hex(fromQ, fromR);
            var fromTile = game.GetBoard().GetTile(fromHex);
            if (fromTile != null && fromTile.Effects.Any(e => e.ID == tileEffectID))
                game.RecordAndApply(new TileEffectExpiredEvent { Position = fromHex, TileEffectID = tileEffectID });

            return ApplyTileEffect(game, ownerID, new Hex(toQ, toR), tileEffectID, duration);
        }

        private static int CalcDamage(Character atker, Character target, int bd, EffectDamageScaling scal)
        {
            float tot = bd;
            switch (scal)
            {
                case EffectDamageScaling.None:
                    break;
                case EffectDamageScaling.AttackDamage:
                    tot -= (1 - atker.ArmorPen.GetF()) * target.Defense.GetI();
                    break;
                case EffectDamageScaling.SpellDamage:
                    tot -= (1 - atker.SpellPen.GetF()) * target.MagicDefense.GetI();
                    break;
                case EffectDamageScaling.Hybrid:
                    tot -= (1 - atker.ArmorPen.GetF()) * target.Defense.GetI() + (1 - atker.SpellPen.GetF()) * target.MagicDefense.GetI();
                    break;
            }
            return (int)Math.Max(1, tot);
        }
        private static int CalcLifeSteal(Character atker, int bd, EffectDamageScaling scal)
        {
            float ls = 0;
            switch (scal)
            {
                case EffectDamageScaling.None:
                    break;
                case EffectDamageScaling.AttackDamage:
                    ls = atker.LifeSteal.GetF() * bd;
                    break;
                case EffectDamageScaling.SpellDamage:
                    ls = atker.SpellVamp.GetF() * bd;
                    break;
                case EffectDamageScaling.Hybrid:
                    ls = atker.LifeSteal.GetF() * bd + atker.SpellVamp.GetF() * bd;
                    break;
            }
            return (int)Math.Max(0, ls);
        }
    }
}
